version: '3.4'

services:
  
  bono-todo-infrastructure-sql-data:
    environment:      
      - SA_PASSWORD=H@rd2103211943
      - ACCEPT_EULA=Y  
    networks:
      # you may set custom IP addresses
      bono-internal:
        ipv4_address: 172.16.237.13
      bono-external:
        ipv4_address: 172.16.238.13
    ports:
      - "1433:1433"    # Important: In a production environment your should remove the external port
      
  bono-todo-api-account:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    networks:
      # you may set custom IP addresses
      bono-internal:
        ipv4_address: 172.16.237.11         
      bono-external:
        ipv4_address: 172.16.238.11
    ports:
      - "8082:80"

  bono-todo-api-task-todo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - ASPNETCORE_URLS=http://0.0.0.0:80
    networks:
      # you may set custom IP addresses
      bono-internal:
        ipv4_address: 172.16.237.12         
      bono-external:
        ipv4_address: 172.16.238.12
    ports:
      - "8083:80"
   
  bono-todo-web-razor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - AuthApi=http://172.16.238.3/
      - TaskToDoApi=http://172.16.238.4/   
    networks:
      # you may set custom IP addresses
      bono-internal:
        ipv4_address: 172.16.237.10         
      bono-external:
        ipv4_address: 172.16.238.10
    ports:
      - "8081:80"

  bono-todo-test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    networks:
      # you may set custom IP addresses
      bono-internal:
        ipv4_address: 172.16.237.14         
      bono-external:
        ipv4_address: 172.16.238.14
        
    depends_on:
      - Bono.ToDo.Infrastructure.Sql.Data
      - Bono.ToDo.Api.Account  
      - Bono.ToDo.Api.TaskToDo
      - Bono.ToDo.Web.Razor
    
    # image: mcr.microsoft.com/dotnet/sdk:5.0
    # # environment:
      # # - ConnectionStrings__TimeSheetContext=Data Source=sql-server-database; Initial Catalog=TimeSheets; User Id=sa; Password=H@rd2103211943
    # volumes:
      # - .:/src
      # - ../test:/test
    # working_dir: /src
    # command:
      # [
        # "./Scripts/wait-for-it.sh",        
        # "--",
        # "dotnet",
        # "test",
        # "0-Test/Bono.ToDo.Application.Tests/Bono.ToDo.Application.Tests.csproj"
      # ]
      