version: '3.4'

services:
  
  Bono.ToDo.Infrastructure.Sql.Data:    
    image: microsoft/mssql-server-linux:2017-latest
    container_name: Bono.ToDo.Infrastructure.Sql.Data
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
    networks:
    # you may set custom IP addresses
      bono-internal:
        ipv4_address: 172.16.237.13         
      bono-external:
        ipv4_address: 172.16.238.13      
  Bono.ToDo.Api.Account:
    image: bono-todo-api-account
    build:
      context: .
      dockerfile: 2-Api/Bono.ToDo.Api.Account/Dockerfile
    networks:
      # you may set custom IP addresses
      bono-internal:
        ipv4_address: 172.16.237.11         
      bono-external: 
        ipv4_address: 172.16.238.11 
    depends_on:    
      - Bono.ToDo.Infrastructure.Sql.Data   
      
  Bono.ToDo.Api.TaskToDo:
    image: bono-todo-api-task
    build:
      context: .
      dockerfile: 2-Api/Bono.ToDo.Api.TaskToDo/Dockerfile
    networks:
      # you may set custom IP addresses
      bono-internal:
        ipv4_address: 172.16.237.12         
      bono-external:
        ipv4_address: 172.16.238.12 
    depends_on:    
      - Bono.ToDo.Infrastructure.Sql.Data  

  Bono.ToDo.Web.Razor:
    image: bono-todo-web-razor
    build:
      context: .
      dockerfile: 1-Web/Bono.ToDo.Web.Razor/Dockerfile
    networks:
      # you may set custom IP addresses
      bono-internal:
        ipv4_address: 172.16.237.10         
      bono-external:
        ipv4_address: 172.16.238.10 
        
    depends_on:
      - Bono.ToDo.Api.Account  
      - Bono.ToDo.Api.TaskToDo

  Bono.ToDo.Integration.Tests:
    container_name: bono-todo-integration-tests
    image: mcr.microsoft.com/dotnet/sdk:5.0
    environment:
      - ConnectionStrings__TimeSheetContext=Data Source=sql-server-database; Initial Catalog=TimeSheets; User Id=sa; Password=1AvenueCodePassword*
    volumes:
      - .:/src
      - ../test:/test
    working_dir: /src
    command:
      [
        "./Scripts/wait-for-it.sh",
        "Bono.ToDo.Infrastructure.Sql.Data:1433",
        "--",
        "dotnet",
        "test",
        "0-Test/Bono.ToDo.Application.Tests/Bono.ToDo.Application.Tests.csproj"
      ]

networks:
    # Explicitly-defined internal network for containers to talk to each other
    bono-internal:
        ipam:
            config:
              - subnet: 172.16.237.0/24
                gateway: 172.16.237.1
    # Network for exposing IPs for access from the host, e.g. your browser
    bono-external:
        ipam:
            config:
              - subnet: 172.16.238.0/24
                gateway: 172.16.238.1

volumes:
  mssql-server-linux-data: