name: "Build"

on: 
  push:
    paths:
      - src/**
      - .github/workflows/**
    branches:
      - main

jobs:  
  build-image:
   
    runs-on: ubuntu-latest
    steps:

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: push container image bono-todo-api-account
      run: docker push richiebono/bono-todo-api-account:${{ github.sha }}
      
    - name: push container image bono-todo-api-task-todo
      run: docker push richiebono/bono-todo-api-task-todo:${{ github.sha }}
      
    - name: push container image bono-todo-test
      run: docker push richiebono/bono-todo-test:${{ github.sha }}

    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: build container image bono-todo-api-account
      working-directory: /src/1-Api/Bono.ToDo.Api.Account/
      run: docker build -t richiebono/bono-todo-api-account:${{ github.sha }} .
      
    - name: build container image bono-todo-api-task-todo
      working-directory: /src/1-Api/Bono.ToDo.Api.TaskToDo
      run: docker build -t richiebono/bono-todo-api-task-todo:${{ github.sha }} .
 
    - name: build container image bono-todo-test
      working-directory: /src/0-Test/Bono.ToDo.Application.Tests/
      run: docker build -t richiebono/bono-todo-test:${{ github.sha }} .      
    
   
    
  test-code-review:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute test-code-review
        working-directory: ./src
        run: docker-compose up --exit-code-from bono-todo-test bono-todo-test
