name: Bono.ToDo Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install SonarQube
      run: | 
             dotnet tool install --global dotnet-sonarscanner
             sudo update-ca-certificates
                          

    - name: Build with dotnet
      run: | 
             msbuild ./src/Bono.ToDo.sln /p:SonarQubeTargetsImported=true
             dotnet build ./src/Bono.ToDo.sln --configuration Release -p:SonarQubeTargetsImported=true
    
    - name: Test with dotnet
      run: dotnet test ./src/Bono.ToDo.sln --configuration Release /warnaserror