name: code-review

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute code-review
        working-directory: ./src
        run: docker-compose up --exit-code-from bono-todo-integration-tests bono-todo-integration-tests
