name: CodeReview

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute CodeReview
        working-directory: ./src
        run: docker-compose up --exit-code-from Bono.ToDo.Integration.Tests Bono.ToDo.Integration.Tests
